#!/usr/bin/env bash

source "${BASEDIR}/cns-hook-util"
if [[ -f "${BASEDIR}/override-hook" ]]; then
    source "${BASEDIR}/override-hook"
fi

# Protection for unknown functions, required by dehydrated.
valid_passthrough_hooks=$(grep function ${BASEDIR}/cns-hook-util | awk '{print $2}')

handler="$1"
shift
if grep "$handler" <<< "$valid_passthrough_hooks"; then
    "$handler" "$@"
fi
